services:
  - type: web
    name: cybix-telegram-bot
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: 3000