services:
  - type: web
    name: cybix-v3-bot
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false