services:
  - type: web
    name: cybix-v1
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        fromDotEnv: true
      - key: OWNER_ID
        fromDotEnv: true
    autoDeploy: true