services:
  - type: web
    name: cybixtech-bot
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: API_URL
        value: https://cybix-v3-3.onrender.com
      - key: PORT
        value: 3000