services:
  - type: web
    name: cybix-bot
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
    autoDeploy: true
    healthCheckPath: /