services:
  - type: web
    name: cybix-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: 8080
      - key: CHANNEL_USERNAME
        sync: false
      - key: SELF_URL
        sync: false