services:
  - type: web
    name: cybix-v1
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: starter
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        sync: false