services:
  - type: web
    name: queen-nomi-v1
    env: node
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: PORT
        value: 3000
      - key: RENDER
        value: true
    autoDeploy: true
    ports:
      - 3000